name: Empleos diarios

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Descargar historial previo
        uses: actions/download-artifact@v4
        with:
          name: historial
        continue-on-error: true

      - name: Ejecutar script
        run: python main.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}

      - name: Subir historial actualizado
        uses: actions/upload-artifact@v4
        with:
          name: historial
          path: historial.json
